title: Leo's Pages
description: Leo's Personal Pages
theme: just-the-docs

url: https://jeongleo.github.io

# === 보조링크 ===
# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# === 타이틀 로고 ===
# # Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/just-the-docs.png"

# === 브라우저에 표시될 로고 ===
# # Set a path/url to a favicon that will be displayed by the browser
# favicon_ico: "/assets/images/favicon.ico"

# === 네이게이션 사이드바 표시 ===
# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# === 제목 앵커 활성화 ===
# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# === 테마 ===
# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# === 코드 복사 버튼 ===
# For copy button on code
enable_copy_code_button: true

# === 맨 위로 돌아가기 활성화 ===
# back_to_top: true
# back_to_top_text: "Back to top"

# === 컬렉션 ===
# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  courseworks:
    permalink: "/:collection/:path/"
    output: true
  rc_plane:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    courseworks:
      # Give the collection a name
      name: CourseWorks
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true
    
    rc_plane:
      name: RC Plane