site_name: Leo's Pages
site_url: https://jeongleo.github.io/

theme:
  name: material
  custom_dir: overrides
  languages: ko

  font:
    text: Nanum Gothic
    code: Consolas

  logo: assets/images/logo-512x512.png
  favicon: assets/images/favicon.ico

  features:
    - navigation.instant    # 페이지를 완전히 다시 로딩하지 않고 바뀌는 부분만 로딩
    - navigation.tabs       # 최상위 섹션이 헤더 아래의 메뉴 레이어로 렌더링됨
    # - navigation.sections   # 최상위 섹션이 사이드바에서 그룹으로 렌더링됨; 참고: tab & sections 는 함께 활성화될 수 있음
    # - navigation.expand     # 사이드바는 기본적으로 모든 하위 섹션을 확장
    # - navigation.path       # 제목 위에 브레드크럼 탐색이 렌더링됨 > 스폰서만 가능함
    - navigation.indexes    # 섹션 인덱스 페이지가 활성화되어 문서를 섹션에 직접 첨부 가능. 개요 페이지를 제공하는 목적
    - toc.follow            # 사이드바가 자동으로 스크롤되어 항상 표시됨
    - navigation.top        # 맨 위로 돌아가기 버튼 활성화
    - navigation.prune      # 네비게이션 
    - content.code.copy     # 코드 복사 기능

  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
          icon: material/brightness-4
          name: Switch to Light mode
      primary: black
      accent: deep orange

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to Dark mode
      primary: custom
      accent: deep orange

markdown_extensions: 
  - attr_list
  - def_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

  # 이미지 configuration
  - md_in_html
  - pymdownx.blocks.caption

  # for MathJax
  - pymdownx.arithmatex:
      generic: true
  # - mdx_math

plugins:
  # 다국어 지원원
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: ko
          default: true
          name: 한국어
          build: true
        # - locale: en
        #   name: English
        #   build: true

  # 이미지 확대
  - glightbox

  - meta
  - social:
      cards_layout_options:
          background_color: "#004191"

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # 수식 복사를 위해 추가됨
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2025 Minho Jeong. All rights reserved.
