site_name: Leo's Pages
site_url: https://jeongleo.github.io

theme:
  name: material
  custom_dir: overrides

  font:
    text: Nanum Gothic
    code: Consolas

  logo: assets/logo-512x512.png
  favicon: assets/favicon.ico

  features:
    - navigation.instant    # 페이지를 완전히 다시 로딩하지 않고 바뀌는 부분만 로딩딩
    - navigation.tabs       # 최상위 섹션이 헤더 아래의 메뉴 레이어로 렌더링됨
    - navigation.sections   # 최상위 섹션이 사이드바에서 그룹으로 렌더링됨; 참고: tab & sections 는 함께 활성화될 수 있음
    - navigation.expand     # 사이드바는 기본적으로 모든 하위 섹션을 확장
    # - navigation.path       # 제목 위에 브레드크럼 탐색이 렌더링됨 > 스폰서만 가능함
    - navigation.indexes    # 섹션 인덱스 페이지가 활성화되어 문서를 섹션에 직접 첨부 가능. 개요 페이지를 제공하는 목적
    - toc.follow            # 사이드바가 자동으로 스크롤되어 항상 표시됨
    - navigation.top        # 맨 위로 돌아가기 버튼 활성화화
    # - navigation.prune      # 네비게이션 

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to Dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to Light mode

  # palette:
  #   # Dark Mode
  #   - scheme: slate
  #     toggle:
  #       icon: material/weather-night
  #       name: Dark Mode
  #     primary: blue grey
  #     accent: deep purple

  #   # Light Mode
  #   - scheme: default
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Light Mode
  #     primary: indigo
  #     accent: deep orange

markdown_extensions: 
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!pyhton/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

plugins:
  - meta

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com
#       name: Github
  # generator: false

copyright: Copyright &copy; 2025 Minho Jeong. All rights reserved.
